### ISSUE TITLE
Is this functional?

### ISSUE THREAD

**Issue by olivluca** [Harry-58/Truma_CP-_Simulator#2]
Hello, I just found this repository.
Is it functional (I mean, the communication protocol)?
Would it work with a diesel heater (you only mention gas in the source)?
Which hardware interface are you using for the linbus?
Are these too many questions :grin: ?

**Comment by Harry-58** [comment]
Hallo,
ja es funktioniert mit meiner "Truma  combi 4". Ob es mit anderen Heizung funktioniert, kann ich nicht testen.
Ich habe es aber nur für erste Tests verwendet, jetzt benutze ich diese Anwendung: https://github.com/Harry-58/inetbox2mqtt-SMS.
Alle Details zur Hardware können hier gefunden werden:
https://github.com/mc0110/inetbox2mqtt     (hieraus ist mein Fork "inetbox2mqtt-SMS" entstanden)
https://github.com/danielfett/inetbox.py

**Comment by Harry-58** [comment]
Richtig.
